FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libreoffice-writer \
    libreoffice-calc \
    libreoffice-impress \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline -B

EXPOSE 8080
EXPOSE 5005

CMD ["./mvnw", "spring-boot:run", \
  "-Dspring-boot.run.profiles=dev", \
  "-Dspring-boot.run.fork=false", \
  "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
