services:
  db:
    image: postgres:15-alpine
    container_name: nexa_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nexa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      # Script de seed: se ejecuta automáticamente la primera vez (volumen vacío)
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: nexa_redis_dev
    profiles: ["prod"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nexa_dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nexa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DEVTOOLS_RESTART_ENABLED: true
    ports:
      - "8082:8080" # App (host:container)
      - "5005:5005" # Debug remoto (IntelliJ / VS Code)
    volumes:
      # Monta el código fuente completo para hot reload
      - .:/app
      # Cache de Maven para no descargar en cada rebuild
      - maven_cache:/root/.m2
      # Montaje explícito: Conecta el disco de tu Mac a la ruta /home/datos-nexa de Docker
      - /Users/alejandrochaves/datos-nexa:/home/datos-nexa
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data:
  maven_cache:
