# =============================================
# Perfil DESARROLLO
# Activo cuando SPRING_PROFILES_ACTIVE=dev
# =============================================

server.port=8080

# Base de datos (dentro de Docker usa el hostname "db")
spring.datasource.url=jdbc:postgresql://localhost:5432/nexa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf sin caché para ver cambios inmediatamente
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
# Leer directamente del código fuente (ideal para Docker con volumen montado) usa para desarrollo y que se meustren los cambios
spring.thymeleaf.prefix=file:src/main/resources/templates/
spring.web.resources.static-locations=file:src/main/resources/static/

# Logs verbosos en desarrollo
logging.level.root=INFO
logging.level.com.empresa=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Configuración de DevTools para Hot Reload en Docker
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Redis — desarrollo local
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2

# ==========================================================
# Ruta para recursos de archivos en la nube
# ==========================================================

# 1. Ruta Activa: Usada por Docker internamente (Conectada al Mac vía Volumen)
ruta.recursos=/home/datos-nexa

# 2. Ruta Comentada: Por si corres la app nativamente sin Docker
# ruta.recursos=/Users/alejandrochaves/datos-nexa
# Limites de subida de archivos (necesario para PDFs y archivos grandes)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
