-- ════════════════════════════════════════════════════════════════════════════
-- Notificaciones por correo: tabla correo_configuraciones
--
-- Prod usa spring.jpa.hibernate.ddl-auto=validate, así que esta tabla debe
-- existir ANTES de desplegar la versión con el servicio de correo.
-- En dev no hace falta: Hibernate la crea solo (ddl-auto=update).
--
-- Es idempotente: si la tabla ya existe no se toca.
-- Uso (en el servidor de prod):
--   psql -h localhost -U <usuario> -d <base> -v ON_ERROR_STOP=1 -f 2026-09-29-correo.sql
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- Servidor SMTP propio de cada dirección (una fila por dirección)
CREATE TABLE IF NOT EXISTS correo_configuraciones (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion_id           bigint NOT NULL UNIQUE REFERENCES direcciones (id),
    host                   varchar(150),
    puerto                 integer,
    seguridad              varchar(10) NOT NULL
                           CONSTRAINT correo_configuraciones_seguridad_check
                           CHECK (seguridad IN ('NINGUNA', 'STARTTLS', 'SSL')),
    usuario                varchar(150),
    -- AES-256-GCM con la misma clave que los tokens de WhatsApp (whatsapp.encryption.key)
    password_cifrado       text,
    remitente_email        varchar(150),
    remitente_nombre       varchar(150),
    activo                 boolean NOT NULL,
    fecha_actualizacion    timestamp(6),
    ultima_prueba_exitosa  timestamp(6)
);

COMMIT;
