-- ════════════════════════════════════════════════════════════════════════════
-- Módulo Classroom: tablas classroom_*
--
-- Prod usa spring.jpa.hibernate.ddl-auto=validate, así que estas tablas deben
-- existir ANTES de desplegar la versión con el Classroom (si no, la app no arranca).
-- En dev no hace falta: Hibernate las crea solo (ddl-auto=update).
--
-- Es idempotente: si una tabla ya existe no se toca, y se puede correr dos veces.
-- Uso (en el servidor de prod):
--   psql -h localhost -U <usuario> -d <base> -v ON_ERROR_STOP=1 -f 2026-09-28-classroom.sql
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

-- Una clase por materia + sección (se materializa desde el horario)
CREATE TABLE IF NOT EXISTS classroom_clases (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_creacion  timestamp(6) NOT NULL,
    direccion_id    bigint NOT NULL REFERENCES direcciones (id),
    materia_id      bigint NOT NULL REFERENCES materias (id),
    nivel_id        bigint NOT NULL REFERENCES niveles_academicos (id),
    CONSTRAINT uk_classroom_clase_direccion_materia_nivel UNIQUE (direccion_id, materia_id, nivel_id)
);

-- Anuncios, tareas y materiales
CREATE TABLE IF NOT EXISTS classroom_publicaciones (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase_id          bigint NOT NULL REFERENCES classroom_clases (id),
    tipo              varchar(20) NOT NULL
                      CONSTRAINT classroom_publicaciones_tipo_check
                      CHECK (tipo IN ('ANUNCIO', 'TAREA', 'MATERIAL')),
    autor_id          bigint NOT NULL REFERENCES usuarios (id),
    titulo            varchar(200),
    contenido         varchar(5000),
    tema              varchar(100),
    fecha_entrega     timestamp(6),
    puntos_totales    integer,
    -- Id simple, sin llave foránea: si el componente se borra desde Gestión
    -- Académica la tarea sigue existiendo y solo deja de ser calificable
    componente_id     bigint,
    clave_componente  varchar(20)
                      CONSTRAINT classroom_publicaciones_clave_componente_check
                      CHECK (clave_componente IN ('COTIDIANO', 'TAREA', 'PROYECTO', 'EXAMEN')),
    fecha_creacion    timestamp(6) NOT NULL,
    fecha_edicion     timestamp(6)
);

-- Trabajo de cada estudiante sobre una tarea (la nota vive en resultados_componente)
CREATE TABLE IF NOT EXISTS classroom_entregas (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id      bigint NOT NULL REFERENCES classroom_publicaciones (id),
    estudiante_id       bigint NOT NULL REFERENCES usuarios (id),
    estado              varchar(20) NOT NULL
                        CONSTRAINT classroom_entregas_estado_check
                        CHECK (estado IN ('ASIGNADA', 'ENTREGADA', 'DEVUELTA')),
    texto               varchar(5000),
    fecha_entrega       timestamp(6),
    fecha_devolucion    timestamp(6),
    comentario_docente  varchar(500),
    CONSTRAINT uk_classroom_entrega_publicacion_estudiante UNIQUE (publicacion_id, estudiante_id)
);

-- Archivos o enlaces de una publicación (docente) o de una entrega (estudiante)
CREATE TABLE IF NOT EXISTS classroom_adjuntos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id  bigint REFERENCES classroom_publicaciones (id),
    entrega_id      bigint REFERENCES classroom_entregas (id),
    nombre          varchar(255) NOT NULL,
    ruta            varchar(500),
    url             varchar(1000),
    extension       varchar(20),
    tamano_bytes    bigint,
    fecha_creacion  timestamp(6) NOT NULL
);

-- Comentarios de la clase sobre una publicación
CREATE TABLE IF NOT EXISTS classroom_comentarios (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id  bigint NOT NULL REFERENCES classroom_publicaciones (id),
    autor_id        bigint NOT NULL REFERENCES usuarios (id),
    contenido       varchar(2000) NOT NULL,
    fecha           timestamp(6) NOT NULL
);

-- Índices para las consultas del módulo (tablón, tareas por clase, entregas y adjuntos)
CREATE INDEX IF NOT EXISTS idx_classroom_publicaciones_clase ON classroom_publicaciones (clase_id, tipo, fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS idx_classroom_entregas_estudiante ON classroom_entregas (estudiante_id);
CREATE INDEX IF NOT EXISTS idx_classroom_adjuntos_publicacion ON classroom_adjuntos (publicacion_id);
CREATE INDEX IF NOT EXISTS idx_classroom_adjuntos_entrega ON classroom_adjuntos (entrega_id);
CREATE INDEX IF NOT EXISTS idx_classroom_comentarios_publicacion ON classroom_comentarios (publicacion_id);

COMMIT;
